#https://devops.datenkollektiv.de/banner.txt/index.html

spring:
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

jwt:
  secret: 753778214125442A472D4B6150645367566B59703373367639792F423F452848
  expiration: 36000000


---

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: AcademyDev

  datasource:
    url: jdbc:postgresql://${DB_HOST}/academy
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  banner:
      location: dev-banner
server:
    port: 8080

---

spring:
  config:
    activate:
      on-profile: test
  application:
    name: AcademyTest
  datasource:
    url: jdbc:h2:mem:academy_test
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 5
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  banner:
    location: test-banner

