

jwt:
  secret: ${JWT_SECRET}
  expiration: 36000000

spring:
  application:
    name: Academy
  datasource:
    url: jdbc:postgresql://${DB_HOST}/academy
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  banner:
    location: dev-banner

server:
  port: 8080


oauth2:
  client:
    google:
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
      redirect-url-login: http://localhost:8080/api/v1/oauth2/callback-login/google
      redirect-url-register: http://localhost:8080/api/v1/oauth2/callback-register/google

    facebook:
      client-id: ${FACEBOOK_CLIENT_ID}
      client-secret: ${FACEBOOK_CLIENT_SECRET}
      redirect-url-login: http://localhost:8080/api/v1/oauth2/callback-login/facebook
      redirect-url-register: http://localhost:8080/api/v1/oauth2/callback-register/facebook



