#https://devops.datenkollektiv.de/banner.txt/index.html

spring:
  profiles:
    active: test
  config:
    import: optional:file:.env[.properties]


jwt:
  secret: ${JWT_SECRET}
  expiration: 36000000

